fix: spelling and placement error
nandtotetris/computer-visualizer pull request #46
Opened 2020-11-06 19:11 UTC by mikereze

**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2020-11-06 19:23 UTC, henok-outlier commented
This is not a `fix` commit, instead a `docs`. So please change the commit to `docs: update node version requirement placement and fix typo`.

2020-11-06 20:14 UTC, mikereze commented
> This is not a `fix` commit, instead a `docs`. So please change the commit to `docs: update node version requirement placement and fix typo`.

2020-11-07 07:51 UTC, henok-tesfaye requested changes
@mikereze please link the issue in the PR(add `Closes #issueNumber`).

2020-11-07 08:50 UTC, henok-outlier approved these changes

2020-11-07 08:50 UTC, henok-tesfaye approved these changes

2020-11-07 08:51 UTC, merged